apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
    name: zero
    labels:
        client: zero
spec:
    client:
        clientId: ENC[AES256_GCM,data:mFvpig==,iv:EFG81wt/201mMyKDrHV6/nTqoRXXw+sWzE0Km7t/coE=,tag:shsOwUnOcs0zdfQBDtXzEQ==,type:str]
        defaultClientScopes:
            - profile
        description: MOC Zero OpenShift cluster
        name: Zero cluster
        protocol: openid-connect
        secret: ENC[AES256_GCM,data:BuFDJc52OmYPtfUYZ1dxSva17hIaUDv9zuYEXOyrdl92y90Y,iv:iNc2tmdmdT9LaO+voKYGNnwLQBU31Oq7YCq8b6r4FYs=,tag:aqC5jOQJdxvZ55iFRRDc0g==,type:str]
        standardFlowEnabled: true
        redirectUris:
            - https://oauth-openshift.apps.zero.massopen.cloud/oauth2callback/operate-first
    realmSelector:
        matchLabels:
            realm: operate-first
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-22T20:28:24Z"
    mac: ENC[AES256_GCM,data:5x4BGPi9MkNqUANJIuIlbM1ZZ4Ky49OqWxAbfutpDfpZWFu47MosodP/HImTbk7Y0nHtjDpDZZkleoDfp6hYjS8DSHtgUBkhiJfQGf1CPXxQGc+sTXVXulAe1pxn9L0/DlIPkym9IyW3Rti8PXwQs3DE/GfS/IZVs1Uvs9TONJU=,iv:cAmU2kP4ebE0qFb92lKdyQ4K7CMYnoYATRpoLokAs08=,tag:UfG1QsWBmwoh92gxYdxdpg==,type:str]
    pgp:
        - created_at: "2021-06-16T22:13:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAtsJvD2FFO724wGspw+1StnWk+JlkyuCE78UMQ3ajoWzV
            M0qNbaqd1eBWiuyXwPJHm/6YPmVmSrKgo857IBXmU8NEsTAs3PyxZ7W7t7tE6COX
            xZrW8gle2a7RbDAnJ9mvV16RA/xXQnKnu9hqOlMqWU/qvjsM6nS0UVHiaFvy0nYq
            gbWv4XAa/Z0ygwozq7/sKvfVYoB8zc/sztMwjU041ogdzpmKAidO7pn5w/ONKalG
            y/NcLMZl9ckNBgiwAVLebequZuQ4omxj7zWV6qppfLRC23+tJQRGQYOjE97brBKM
            iJIuWKIrDuhApTZ+voXgZDap81qolJADaQ4zcSYEmvVP1druUNaDdOIUpF0dOsEX
            38UMtwDj4J725J24ouUVvVUYcOkig7p59z0OaIEXTeKME2WWp5IDxbF6EFrBWnDy
            82L2yzr6Ch1pEVqINJjBF4Qg8pqbio4qrSGg5HrHLghFAAV0wUS24ILbDbbilKYI
            CjBQbhitIs8vdv6kAwmisTLRWSNB+VXEFEnjfjL8V3Hn0PyQ+91qP9fslPkPpW22
            6iJbHPahSk9D7xuOwAnehiNXhW+ZYiv5reMu31j4XYZ+gpLSTtJNSMF0STzHlkoa
            d7JRKr0ugQXuCnWP4ahFzCtDlrDkpg0Ljmx34dgK4uQpiBKAw6LrH/7q22OPTVvS
            5gGCoxfykfXsmTEAPShfg8st5p0BrA608yFLfgYzh0p6HtK0WqcWDjBS1mE2BWrl
            wKOxlBtYOBYW3aaJCPRmbbPk8ZK33s6oZZ3N7edqmFjX9+IuI/VKAA==
            =BcQ5
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(clientId|clientSecret|secret)$
    version: 3.7.1
